//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RigMaterialMovementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_RoleManagement
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public Nullable<int> role_id { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
    }
}
