//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RigMaterialMovementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PermintaanPekerjaan
    {
        public int id { get; set; }
        public string no_wo { get; set; }
        public string no_activity { get; set; }
        public string judul_pekerjaan { get; set; }
        public Nullable<System.DateTime> tanggal_pekerjaan { get; set; }
        public string lokasi_asal { get; set; }
        public string cp_lokasi_asal { get; set; }
        public string lokasi_tujuan { get; set; }
        public string cp_lokasi_tujuan { get; set; }
        public string detail_barang { get; set; }
        public string approver { get; set; }
        public string keterangan { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public string finished_by { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
    
        public virtual M_Status M_Status { get; set; }
    }
}
