//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMM.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_RMMEntities : DbContext
    {
        public DB_RMMEntities()
            : base("name=DB_RMMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Area> M_Area { get; set; }
        public virtual DbSet<M_FaktorKeterlambatan> M_FaktorKeterlambatan { get; set; }
        public virtual DbSet<M_Rig> M_Rig { get; set; }
        public virtual DbSet<M_Role> M_Role { get; set; }
        public virtual DbSet<M_RoleManagement> M_RoleManagement { get; set; }
        public virtual DbSet<M_Status> M_Status { get; set; }
        public virtual DbSet<M_Transporter> M_Transporter { get; set; }
        public virtual DbSet<T_PermintaanPekerjaan> T_PermintaanPekerjaan { get; set; }
        public virtual DbSet<T_PermintaanPekerjaanDetail> T_PermintaanPekerjaanDetail { get; set; }
        public virtual DbSet<T_RigMaterialMovement> T_RigMaterialMovement { get; set; }
        public virtual DbSet<T_RigMaterialMovementDetail> T_RigMaterialMovementDetail { get; set; }
        public virtual DbSet<VW_AREA> VW_AREA { get; set; }
        public virtual DbSet<VW_RIG> VW_RIG { get; set; }
    
        public virtual ObjectResult<SP_GET_LAPORAN_AVERAGE_MOVINGRIG_Result> SP_GET_LAPORAN_AVERAGE_MOVINGRIG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LAPORAN_AVERAGE_MOVINGRIG_Result>("SP_GET_LAPORAN_AVERAGE_MOVINGRIG");
        }
    
        public virtual ObjectResult<SP_GET_LAPORAN_KINERJA_MOVINGRIG_Result> SP_GET_LAPORAN_KINERJA_MOVINGRIG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LAPORAN_KINERJA_MOVINGRIG_Result>("SP_GET_LAPORAN_KINERJA_MOVINGRIG");
        }
    
        public virtual ObjectResult<SP_GET_LAPORAN_REKAPDATA_Result> SP_GET_LAPORAN_REKAPDATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LAPORAN_REKAPDATA_Result>("SP_GET_LAPORAN_REKAPDATA");
        }
    }
}
