//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PermintaanPekerjaanDetail
    {
        public int id { get; set; }
        public int permintaan_pekerjaan_id { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<int> status_id { get; set; }
        public string notes { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
    }
}
