//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMM.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RigMaterialMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_RigMaterialMovement()
        {
            this.T_RigMaterialMovementDetail = new HashSet<T_RigMaterialMovementDetail>();
        }
    
        public int id { get; set; }
        public string area { get; set; }
        public string rig { get; set; }
        public string rute_dari { get; set; }
        public string rute_ke { get; set; }
        public Nullable<double> jarak { get; set; }
        public Nullable<int> transporter_id { get; set; }
        public Nullable<System.DateTime> tanggal_mulai { get; set; }
        public Nullable<int> target_hari { get; set; }
        public Nullable<int> target_trip { get; set; }
        public Nullable<long> biaya { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_date { get; set; }
    
        public virtual M_Transporter M_Transporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RigMaterialMovementDetail> T_RigMaterialMovementDetail { get; set; }
    }
}
